### PR TITLE
Quit on Ctrl-D

### PR DESCRIPTION
**Pull request by jonatanolofsson**

### CODE REVIEW

**Comment by jamielinux** [comment]
Great idea! 

Would be better like this:

```
read -r -e -p "Command: " action || exit 0
```

Update the PR and then I will merge :)

**Comment by jonatanolofsson** [comment]
Done. I kept the printf for a cleaner prompt after exit

**Comment by jamielinux** [comment]
Thanks for this!

**Comment by jamielinux** [comment]
I'll cut a release tomorrow with your PRs :)

**Pull request merged**
