### PR TITLE
Unicode eyecandy

### PR DESCRIPTION
**Pull request by nick87720z**
Feature & option for eyecandy using unicode chars. Besides this I also tried to all-capital with bold style in caption.
bashmount-unicode-eyecandy

### CODE REVIEW

**Comment by jamielinux** [comment]
I like this idea. Would you mind opening another PR against latest changes? (Also, this PR seems to have your `instant_key` changes inadvertently included.)

I might prefer `pretty` instead of `use_unicode` as the option name.

**Comment by nick87720z** [comment]
Before I will do a PR, how about one more candy: hints below could be like square buttons. Actual text would have background color, with two block chars having this color for foreground. Though I tried to find more interesting chars for button side ends, it seems only other, that link ideally, are corner chars from powerline font.

**Comment by jamielinux** [comment]
> Before I will do a PR, how about one more candy: hints below could be like square buttons. Actual text would have background color, with two block chars having this color for foreground. Though I tried to find more interesting chars for button side ends, it seems only other, that link ideally, are corner chars from powerline font.

I'm not quite sure what you mean. Maybe a screenshot will help?

**Comment by nick87720z** [comment]
Something like that (from history, when I did experiments right in term):
```
tput setaf 4; printf "▐"; tput sgr0; tput setab 4; tput bold; printf "Cancel"; tput sgr0; tput setaf 4; printf "▌"; tput sgr0; printf " "; echo
```
Screenshot

It seems not all block widths have variants for both left/right sides. Besides this one, there is 1/8 variant.

**Comment by jamielinux** [comment]
Ah I see what you mean now, thanks!

I must admit I'm not totally sold on the buttons. They don't function like buttons, but more like a legend for a chart, so I think styling them like buttons is maybe not appropriate. Also, buttons draw extra visual attention and I think it's better to keep attention on the more important parts like the list of devices.

I do like the pretty separators from the original PR though :+1:

**Comment by nick87720z** [comment]
Pushed on top of upstream branch. Also found unicode chars for note bullets. Not arrows though, just triangles. Too hard to find dashes that align with arrow head when done separately.

**Comment by nick87720z** [comment]
btw, in the error - why only bullet/arrow is red, could be either text or just ERROR word.

**Comment by nick87720z** [comment]
I have another branch on top of this, to use alternate screen.

**Comment by jamielinux** [comment]
Could maybe use `⇒` instead of `==>`: https://unicode-table.com/en/21D2/ ?

I switched the separator from `=` to `-` in latest script. Can you amend those please?

Also, I would:

- rename `print_separator` function to `pretty_print`
- rename `print_separator_dumb` function to `print_separator`

Finally, can you also change option from `use_unicode` to `pretty` in `bashmount.conf`.

**Comment by jamielinux** [comment]
> btw, in the error - why only bullet/arrow is red, could be either text or just ERROR word.

That's true. Maybe it's better to have the whole error message in red.

**Comment by nick87720z** [comment]
ooops, I somehow missed use_unicode in bashmount.conf

**Comment by nick87720z** [comment]
> Could maybe use ⇒ instead of ==>: https://unicode-table.com/en/21D2/ ?
This character has single width, interminal its very tiny.
I tried some chars featured in opentype. When printed directly by code instead of opentype substitution, they require some space before, since they occupy too. However, it seems they are only for libvte-based terms, in urxvt and xterm they are not visible (I'm not sure, if any of them support fallback fonts like all gtk apps do for now).

**Comment by jamielinux** [comment]
That's great, thanks for researching that. Using nicer unicode characters will be the default for bashmount once I merge this, so I think we need to pick characters that are well supported.

Perhaps for the help text, we can replace `==>` with just `>`, and for the pretty version we can use the triangle you suggested?

I'm not sure about `msg()` and `error()`. I like `==>` because it is clear, large and visible. I think this is less important to have unicode though. The separators are visible in every screen all the time so we definitely want to make the separators look nice, but these messages are only transient. Maybe simplest to leave them as they are?

**Comment by nick87720z** [comment]
Just tried powerline with line graphics. I'm specially unsure about powerline char. Though it's in user page, it's used in powerline app, which I only have seen on some cool screenshots.

**Comment by jamielinux** [comment]
Yeah, I agree it's probably too bulky for note bullet. Also, doesn't powerline stuff need specific font support?

**Comment by jamielinux** [comment]
Going to merge this and tweak. Any further bits can go into another PR :)

**Comment by jamielinux** [comment]
Also, thank you for this! :+1: :rocket:

**Pull request merged**
